In [1]:
import pandas as pd

In [2]:
resources = pd.read_csv('../data/resource_mapping_by_county.csv')

In [3]:
resources

,Year,Agency_ID,Agency_Name,Program_Name,County_District,Calculation_Method,Children Served,Expenditure
0,2015,DCS,Department of Children's Services,Custody & Truancy Prevention,Benton,Actual,250,"$92,617"
1,2015,DCS,Department of Children's Services,Custody & Truancy Prevention,Blount,Actual,20,"$98,668"
2,2015,DCS,Department of Children's Services,Custody & Truancy Prevention,Bradley,Actual,42,"$66,581"
3,2015,DCS,Department of Children's Services,Custody & Truancy Prevention,Carroll,Actual,152,"$643,884"
4,2015,DCS,Department of Children's Services,Custody & Truancy Prevention,Crockett,Actual,50,"$123,337"
...,...,...,...,...,...,...,...,...
29363,2022,DOE,Department of Education,NaN,Weakley,Estimate,3946,"$23,267,000"
29364,2022,DOE,Department of Education,NaN,White,Estimate,3756,"$23,450,000"
29365,2022,DOE,Department of Education,NaN,Williamson,Estimate,44244,"$159,353,000"
29366,2022,DOE,Department of Education,NaN,Wilson,Estimate,22483,"$107,237,000"
29367,Note: '*' means either data are not reported...,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
assessment = pd.read_csv('../data/school_assessment.csv')

In [5]:
assessment

,year,system,system_name,school,school_name,test,subject,grade,student_group,participation_rate,...,valid_tests,n_below,n_approaching,n_met_expectations,n_exceeded_expectations,pct_below,pct_approaching,pct_met_expectations,pct_exceeded_expectations,pct_met_exceeded
0,2022,10,Anderson County,2,Anderson County High School,EOC,Algebra I,10,All Students,98,...,40,**,**,**,**,**,**,**,**,**
1,2022,10,Anderson County,2,Anderson County High School,EOC,Algebra I,10,Black/Hispanic/Native American,*,...,3,*,*,*,*,*,*,*,*,*
2,2022,10,Anderson County,2,Anderson County High School,EOC,Algebra I,10,Economically Disadvantaged,94,...,17,**,**,**,**,**,**,**,**,**
3,2022,10,Anderson County,2,Anderson County High School,EOC,Algebra I,10,English Learners,*,...,2,*,*,*,*,*,*,*,*,*
4,2022,10,Anderson County,2,Anderson County High School,EOC,Algebra I,10,English Learners with Transitional 1-4,*,...,2,*,*,*,*,*,*,*,*,*
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
675529,2022,987,Tennessee Public Charter School Commission,8030,Nashville Collegiate Prep,TNReady,Science,All Grades,Non-English Learners/Transitional 1-4,96,...,71,**,**,**,**,**,**,**,**,23.9
675530,2022,987,Tennessee Public Charter School Commission,8030,Nashville Collegiate Prep,TNReady,Science,All Grades,Non-Students with Disabilities,96,...,102,**,**,**,**,**,**,**,**,22.5
675531,2022,987,Tennessee Public Charter School Commission,8030,Nashville Collegiate Prep,TNReady,Science,All Grades,Students with Disabilities,*,...,5,*,*,*,*,*,*,*,*,*
675532,2022,987,Tennessee Public Charter School Commission,8030,Nashville Collegiate Prep,TNReady,Science,All Grades,Super Subgroup,96,...,91,**,**,**,**,**,**,**,**,19.8
675533,2022,987,Tennessee Public Charter School Commission,8030,Nashville Collegiate Prep,TNReady,Science,All Grades,White,97,...,33,**,**,**,**,**,**,**,**,15.2

In [10]:
resources2022 = resources.loc[resources['Year'] == '2022'].reset_index(drop=True)

In [11]:
resources2022

,Year,Agency_ID,Agency_Name,Program_Name,County_District,Calculation_Method,Children Served,Expenditure
0,2022,DCS,Department of Children's Services,Adoption - Support Services,Anderson,Actual,320,$0
1,2022,DCS,Department of Children's Services,Adoption - Support Services,Bedford,Actual,48,$0
2,2022,DCS,Department of Children's Services,Adoption - Support Services,Benton,Actual,35,$0
3,2022,DCS,Department of Children's Services,Adoption - Support Services,Bledsoe,Actual,20,$0
4,2022,DCS,Department of Children's Services,Adoption - Support Services,Blount,Actual,378,$0
...,...,...,...,...,...,...,...,...
3414,2022,DOE,Department of Education,NaN,Wayne,Estimate,2048,"$14,711,000"
3415,2022,DOE,Department of Education,NaN,Weakley,Estimate,3946,"$23,267,000"
3416,2022,DOE,Department of Education,NaN,White,Estimate,3756,"$23,450,000"
3417,2022,DOE,Department of Education,NaN,Williamson,Estimate,44244,"$159,353,000"
3418,2022,DOE,Department of Education,NaN,Wilson,Estimate,22483,"$107,237,000"

In [16]:
resources2022 = resources2022.rename(columns = {'  Expenditure ':'Expenditure'})

In [17]:
len(resources2022.loc[resources2022['Expenditure'] == '$0'])

730

In [21]:
resources2022['County_District'].value_counts()

County_District
Davidson        53
Anderson        48
Shelby          48
Hamilton        45
Sullivan        42
                ..
Pickett         31
Trousdale       30
Moore           30
Union           24
Union County    10
Name: count, Length: 96, dtype: int64

In [28]:
resources2022['County_District'] = resources2022['County_District'].apply(lambda x: x + ' County')
resources2022

,Year,Agency_ID,Agency_Name,Program_Name,County_District,Calculation_Method,Children Served,Expenditure
0,2022,DCS,Department of Children's Services,Adoption - Support Services,Anderson County,Actual,320,$0
1,2022,DCS,Department of Children's Services,Adoption - Support Services,Bedford County,Actual,48,$0
2,2022,DCS,Department of Children's Services,Adoption - Support Services,Benton County,Actual,35,$0
3,2022,DCS,Department of Children's Services,Adoption - Support Services,Bledsoe County,Actual,20,$0
4,2022,DCS,Department of Children's Services,Adoption - Support Services,Blount County,Actual,378,$0
...,...,...,...,...,...,...,...,...
3414,2022,DOE,Department of Education,NaN,Wayne County,Estimate,2048,"$14,711,000"
3415,2022,DOE,Department of Education,NaN,Weakley County,Estimate,3946,"$23,267,000"
3416,2022,DOE,Department of Education,NaN,White County,Estimate,3756,"$23,450,000"
3417,2022,DOE,Department of Education,NaN,Williamson County,Estimate,44244,"$159,353,000"
3418,2022,DOE,Department of Education,NaN,Wilson County,Estimate,22483,"$107,237,000"

In [34]:
assessment_allstudent = assessment.loc[(assessment['student_group'] == 'All Students') & (assessment['grade'] == 'All Grades')]
assessment_allstudent

,year,system,system_name,school,school_name,test,subject,grade,student_group,participation_rate,...,valid_tests,n_below,n_approaching,n_met_expectations,n_exceeded_expectations,pct_below,pct_approaching,pct_met_expectations,pct_exceeded_expectations,pct_met_exceeded
45,2022,10,Anderson County,2,Anderson County High School,EOC,Algebra I,All Grades,All Students,99,...,268,**,**,**,**,**,**,**,**,19.4
118,2022,10,Anderson County,2,Anderson County High School,EOC,Algebra II,All Grades,All Students,99,...,220,**,**,**,**,**,**,**,**,27.3
181,2022,10,Anderson County,2,Anderson County High School,EOC,Biology I,All Grades,All Students,100,...,261,**,**,**,**,**,**,**,**,39.8
230,2022,10,Anderson County,2,Anderson County High School,EOC,English I,All Grades,All Students,100,...,265,25,149,72,19,9.4,56.2,27.2,7.2,34.3
283,2022,10,Anderson County,2,Anderson County High School,EOC,English II,All Grades,All Students,99,...,275,**,**,**,**,**,**,**,**,37.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
675242,2022,987,Tennessee Public Charter School Commission,8020,KIPP Antioch College Prep Middle,TNReady,Science,All Grades,All Students,100,...,384,**,**,**,**,**,**,**,**,29.9
675303,2022,987,Tennessee Public Charter School Commission,8020,KIPP Antioch College Prep Middle,TNReady,Social Studies,All Grades,All Students,100,...,256,**,**,**,**,**,**,**,**,29.7
675375,2022,987,Tennessee Public Charter School Commission,8030,Nashville Collegiate Prep,TNReady,ELA,All Grades,All Students,95,...,106,**,**,**,**,**,**,**,**,25.5
675445,2022,987,Tennessee Public Charter School Commission,8030,Nashville Collegiate Prep,TNReady,Math,All Grades,All Students,96,...,107,52,34,15,6,48.6,31.8,14,5.6,19.6
675515,2022,987,Tennessee Public Charter School Commission,8030,Nashville Collegiate Prep,TNReady,Science,All Grades,All Students,97,...,107,**,**,**,**,**,**,**,**,21.5

Results are suppressed where the number of valid test scores is less than 10 (this is denoted by a single asterisk *). In these files, suppression also occurs where any individual proficiency level is less than 1% or greater than 99% at the state and district level, or less than 5% or greater than 95% at the school level (this is denoted by two asterisks**).

In [35]:
merge_test = assessment_allstudent.merge(resources2022, how = 'inner', left_on = 'system_name', right_on = 'County_District')

In [36]:
merge_test

,year,system,system_name,school,school_name,test,subject,grade,student_group,participation_rate,...,pct_exceeded_expectations,pct_met_exceeded,Year,Agency_ID,Agency_Name,Program_Name,County_District,Calculation_Method,Children Served,Expenditure
0,2022,10,Anderson County,2,Anderson County High School,EOC,Algebra I,All Grades,All Students,99,...,**,19.4,2022,DCS,Department of Children's Services,Adoption - Support Services,Anderson County,Actual,320,$0
1,2022,10,Anderson County,2,Anderson County High School,EOC,Algebra I,All Grades,All Students,99,...,**,19.4,2022,DCS,Department of Children's Services,Juvenile Justice Placement,Anderson County,Actual,28,$0
2,2022,10,Anderson County,2,Anderson County High School,EOC,Algebra I,All Grades,All Students,99,...,**,19.4,2022,DCS,Department of Children's Services,Dependent and Neglect Placement - Foster Care,Anderson County,Actual,305,$0
3,2022,10,Anderson County,2,Anderson County High School,EOC,Algebra I,All Grades,All Students,99,...,**,19.4,2022,DCS,Department of Children's Services,Subsidized Permanent Guardianship,Anderson County,Actual,6,$0
4,2022,10,Anderson County,2,Anderson County High School,EOC,Algebra I,All Grades,All Students,99,...,**,19.4,2022,DHS,Department of Human Services,TANF/Families First,Anderson County,Actual,252,$0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
421631,2022,950,Wilson County,95,Watertown Middle School,TNReady,Social Studies,All Grades,All Students,99,...,8.7,56.5,2022,DOE,Department of Education,ESSA-Title III English Language Acquisition,Wilson County,Estimate,899,"$124,779"
421632,2022,950,Wilson County,95,Watertown Middle School,TNReady,Social Studies,All Grades,All Students,99,...,8.7,56.5,2022,DOE,Department of Education,Governor's Civics Seal Grant,Wilson County,Actual,6100,"$10,905"
421633,2022,950,Wilson County,95,Watertown Middle School,TNReady,Social Studies,All Grades,All Students,99,...,8.7,56.5,2022,DOE,Department of Education,ESSER 1.0,Wilson County,Estimate,23619,"$1,875,946"
421634,2022,950,Wilson County,95,Watertown Middle School,TNReady,Social Studies,All Grades,All Students,99,...,8.7,56.5,2022,DOE,Department of Education,SNP Fresh Fruits and Vegetables,Wilson County,Estimate,0,$0
421635,2022,950,Wilson County,95,Watertown Middle School,TNReady,Social Studies,All Grades,All Students,99,...,8.7,56.5,2022,DOE,Department of Education,NaN,Wilson County,Estimate,22483,"$107,237,000"

In [26]:
assessment.loc[(assessment['pct_met_exceeded'] != '*') & (assessment['pct_met_exceeded'] != '**')]

,year,system,system_name,school,school_name,test,subject,grade,student_group,participation_rate,...,valid_tests,n_below,n_approaching,n_met_expectations,n_exceeded_expectations,pct_below,pct_approaching,pct_met_expectations,pct_exceeded_expectations,pct_met_exceeded
5,2022,10,Anderson County,2,Anderson County High School,EOC,Algebra I,10,Female,94,...,17,**,**,**,**,**,**,**,**,5.9
11,2022,10,Anderson County,2,Anderson County High School,EOC,Algebra I,10,Non-Students with Disabilities,100,...,10,**,**,**,**,**,**,**,**,10
27,2022,10,Anderson County,2,Anderson County High School,EOC,Algebra I,9,All Students,100,...,222,**,**,**,**,**,**,**,**,22.5
31,2022,10,Anderson County,2,Anderson County High School,EOC,Algebra I,9,Economically Disadvantaged,100,...,52,**,**,**,**,**,**,**,**,17.3
34,2022,10,Anderson County,2,Anderson County High School,EOC,Algebra I,9,Female,99,...,103,**,**,**,**,**,**,**,**,27.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
675528,2022,987,Tennessee Public Charter School Commission,8030,Nashville Collegiate Prep,TNReady,Science,All Grades,Non-Economically Disadvantaged,96,...,78,**,**,**,**,**,**,**,**,26.9
675529,2022,987,Tennessee Public Charter School Commission,8030,Nashville Collegiate Prep,TNReady,Science,All Grades,Non-English Learners/Transitional 1-4,96,...,71,**,**,**,**,**,**,**,**,23.9
675530,2022,987,Tennessee Public Charter School Commission,8030,Nashville Collegiate Prep,TNReady,Science,All Grades,Non-Students with Disabilities,96,...,102,**,**,**,**,**,**,**,**,22.5
675532,2022,987,Tennessee Public Charter School Commission,8030,Nashville Collegiate Prep,TNReady,Science,All Grades,Super Subgroup,96,...,91,**,**,**,**,**,**,**,**,19.8
675533,2022,987,Tennessee Public Charter School Commission,8030,Nashville Collegiate Prep,TNReady,Science,All Grades,White,97,...,33,**,**,**,**,**,**,**,**,15.2